### ISSUE TITLE
Select files is not good (weird) [Bug]: 

### ISSUE THREAD

**Issue by bassamsdata** [chrisgrieser/finder-vim-mode#1]
### Bug Description

When I installed the keybindings to karabiner, my expectations were low because I didn't think the application would work properly in such an application like finder tbh 🫣, but after trying it for like 10 minutes, I  said **wow** and that was the **aha** moment. It's really amazing, well designed and well applied. Thank you for that.  However I think there's two things might improve the experience.

1. the keybindings image is in bad quality and hard to see, so if possible to upload higher quality image. (I can design one if you can provide me with the high quality plain one and then add it to the repo)

2. Selecting files are through `shift+space` or `shift+arrow` and this is not bad but a little bit weird because usually when selecting multiple files we do it with `command` and `mouse click` then select multiple files that not in order (if you know what I mean). I'd be grateful if possible feature can be added to the keybindings.

Thank you again for this amazing and well thought add-on.

### To Reproduce

If we have 4 files and we want to select files 1 and 4.
steps:
1. select file number 1.
2. not selecting the next 2 files (2+3).
3. select the 4th file.

### Keyboard Layout

British - QWERTY

### Checklist

- [X] I updated to the latest version.
- [X] I have read about the limitations of Karabiner plugins in the [caveats section of the README](../../README.md#caveats).

edited: the steps to reproduce/ just a typo.

**Comment by chrisgrieser** [comment]
thank you for the kind words! 😊

> 1\. the keybindings image is in bad quality and hard to see, so if possible to upload higher quality image. (I can design one if you can provide me with the high quality plain one and then add it to the repo)

While I appreciate the offer, that would only be a short-term solution though. I am using [Keyboard-Layout-Editor](http://www.keyboard-layout-editor.com/#/) to quickly generate new layouts when I make any changes. The advantage is that you can save the "source code" for the image [as json file](https://github.com/chrisgrieser/finder-vim-mode/blob/main/finder-vim-cheatsheet.json). Also with cheatsheets for different  keyboard layouts in mind, such a solution is very much preferable long term.

That site does not seem to offer an option for downloading higher res png. However, simply taking a screenshot on the website leads to a much higher resolution image, so I did that for now. 🙈  You can re-download the cheatsheet, it will now have a much higher resolution.

If you know any other keyboard image generating site, that improves on this, please let me know! Would love to make better cheatsheets.

> 2\. Selecting files are through `shift+space` or `shift+arrow` and this is not bad but a little bit weird because usually when selecting multiple files we do it with `command` and `mouse click` then select multiple files that not in order (if you know what I mean). I'd be grateful if possible feature can be added to the keybindings.

Yeah, that one has also been annoying me. Unfortunately, I don't think there is a solution for this. File managers like ranger manage to accomplish this by distinguishing between selected files and the file where the cursor is standing on. Finder does not know such a distinction, normally the file you are standing on *is* your selected file.

**Comment by bassamsdata** [comment]
Thanks for the updated image 🙏. yea designing an image is not good solution on the long run.

**Comment by chrisgrieser** [comment]
btw, I recently did work a bit on this plugin again, and I found a workaround to be able to make noncontinuous selections without the mouse. The trick is to repurpose Finder's tag system as marks.

Update and see the new installation instructions & cheatsheet to see how to enable this and. 😊 

Be aware, that feature is still super new, and I haven't figured out how to fix all the issues yet
