### ISSUE TITLE
[Bug]: Spotlight Search does not work when focused on Finder

### ISSUE THREAD

**Issue by deferred** [chrisgrieser/finder-vim-mode#4]
### Bug Description

Spotlight Search does not work if called from a Finder window. Instead finder-vim-mode actions are performed in the background Finder window.

### To Reproduce

1. Open Finder
2. Open Spotlight Search
3. Try typing something, it will perform vim actions on the background window instead of typing in the search window

### Keyboard Layout

U.S.

### System UI language

English (US)

### Checklist

- [X] I updated to the latest version of this plugin.
- [X] I updated to the latest version of Karabiner Elements.
- [X] I have read about the limitations of Karabiner plugins in the [Caveats section of the README](..#caveats).

**Comment by chrisgrieser** [comment]
Oh, I actually considered Alfred users, but haven't thought about people simply
using spotlight. Since I don't use Spotlight, I am not 100% sure on all usage
scenarios, but I created a compatibility addon which should mostly fix the
problem. See [the new point in the readme.](..#installation) (If there are any 
edge cases I overlooked, please report back!)

**Comment by deferred** [comment]
Hi @chrisgrieser, thank you for your awesome work! 

Unfortunately, I wasn't successful in installing this addon. When I run the command proposed in the README, karabiner keeps crushing :( When I manually curl the file and place it in `~/.config/karabiner/assets/complex_modifications` directory, karabiner doesn't show Enable button for the addon. Is it reproducible on your end? Could you please assist?

**Comment by chrisgrieser** [comment]
ah yes, the json had some invalid syntax. Issue is fixed, this should now work correctly.

```bash
# install Spotlight addon
open "karabiner://karabiner/assets/complex_modifications/import?url=https://raw.githubusercontent.com/chrisgrieser/finder-vim-mode/main/addons/finder-vim-spotlight-addon.json"
```

**Comment by deferred** [comment]
Seems to work now! 👍 Once again, thank you for the great plugin!
