### ISSUE TITLE
Feature Request: Visual Mode

### ISSUE THREAD

**Issue by ryanwwest** [chrisgrieser/finder-vim-mode#5]
### Feature Requested

Thanks for this awesome vim mode! I'm getting used to hjkl and love it, but I keep wanting to select 3-4 files within a folder to cut/copy/paste/open them together. I used `v` for this at first but realized that instead shows preview information for the current file. Is there already a way to select a subset of the files after navigating to some with e.g. jk?

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have read about the limitations of Karabiner plugins in the [Caveats section of the README](..#caveats).

**Comment by chrisgrieser** [comment]
You can use `shift+space` to add down to the selection, which is the closest thing you can get in Finder. Proper Multi-select or visual mode is unfortunately not possible, since Finder does not distinguish properly between cursor and selection, like more advanced file managers do :/

**Comment by ryanwwest** [comment]
Thanks, good to know! That will still be useful.
